# Constants
WINDOW_TITLE = "Deluge Theme Installer"
FOLDER_LABEL_TEXT = "Select Deluge Installation Folder:"
BROWSE_BUTTON_TEXT = "Browse"
APPLY_DARK_BUTTON_TEXT = "Apply Dark Theme"
APPLY_LIGHT_BUTTON_TEXT = "Apply Light Theme"
APPLY_CUSTOM_THEME_BUTTON_TEXT = "Custom Theme"
QUIT_BUTTON_TEXT = "Quit"
RESULT_LABEL_INITIAL_TEXT = ""
FOLDER_SHARE = "share"
FOLDER_THEMES = "themes"
FOLDER_NASTER = "Naster"
FOLDER_GTK_3_0 = "gtk-3.0"
FILE_GTK_CSS = "gtk.css"
FILE_SETTINGS_INI = "settings.ini"
DELUGE_EXECUTABLE = "deluge.exe"
DELUGE_DEFAULT_PATH="C:/Program Files/Deluge"