
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run PyInstaller
      run: pyinstaller --onefile main.py
      working-directory: ${{ github.workspace }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        asset_path: ${{ github.workspace }}/dist/main.exe
